<?php

use yii\db\Migration;

/**
 * Handles the creation of table `clubs`.
 */
class m161130_143225_create_clubs_table extends Migration
{
    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTable('{{%clubs}}', [
            'id' => $this->primaryKey()->notNull()->unique(),
            'name' => $this->string(128)->notNull()->unique(),
            'country' => $this->string(128)->notNull(), //Изменил c 7 до 128
            'is_active' => $this->integer(1)->notNull(),
            'created_at' => $this->integer()->notNull(),
            'updated_at' => $this->integer()->notNull(),
            'is_active_server' => $this->integer(1)
        ]);
        $created_at = $updated_at = date("Ymd");

        $this->batchInsert('{{%clubs}}', [ 'name', 'country', 'is_active', 'created_at', 'updated_at', 'is_active_server'], [
                ['A Window to the Club World', 'Urbanización Mijas Golf,Mijias-Costa,Málaga', 1, $created_at, $updated_at, 1],
                ['Absolute', 'P.O. Box 3321, Drake Chambers, Road Town, Tortola, British Virgin Islands', 1, $created_at, $updated_at, 1],
                ['Aeolos Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Albatros Beach Club and Hotel', '', 1, $created_at, $updated_at, 1],
                ['Alliance Family Club', '', 1, $created_at, $updated_at, 1],
                ['AlpeAdria Club at Novi Vinodolski', '', 1, $created_at, $updated_at, 1],
                ['Altamira Club', 'Calle el Beril\r\nLa Caleta\r\nAdeje, 38679\r\nTenerife, Canary Islands\r\n922-719011', 1, $created_at, $updated_at, 1],
                ['Amadores Beach Clu', '', 1, $created_at, $updated_at, 1],
                ['Anfi Beach Club', 'Barranco de la Verga,Arguineguin,Canary Islands,Spain', 1, $created_at, $updated_at, 1],
                ['Anna Grand Hotel Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['Aphrodite Hills Resort', '3, Aphrodite Avenue\r\nAphrodite Hills\r\nKouklia CY8500 \r\nCyprus \r\n', 1, $created_at, $updated_at, 1],
                ['Asian Travel Club', '', 1, $created_at, $updated_at, 1],
                ['Atlantic Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Atlantic Club', '', 1, $created_at, $updated_at, 1],
                ['Atlantic Club Campanario', '', 1, $created_at, $updated_at, 1],
                ['Atlantic Club International', '', 1, $created_at, $updated_at, 1],
                ['Atlantic View', '', 1, $created_at, $updated_at, 1],
                ['Atlas Club', 'Club Atlas Nou Espai,Alicante', 1, $created_at, $updated_at, 1],
                ['Atlas The  Vacation Owners Club', '', 1, $created_at, $updated_at, 1],
                ['Averin Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Baxter Vacations', '', 1, $created_at, $updated_at, 1],
                ['Beverly Hills Club', '', 1, $created_at, $updated_at, 1],
                ['Birdland Home & Holidays', 'Golf út. 2\r\n9740 Bükfürdö, Hungary \r\n06-94-358777 06-94-358999 \r\n', 1, $created_at, $updated_at, 1],
                ['British Virgin Island', 'Protestant Cay, Christiansted 00822, St. Croix', 1, $created_at, $updated_at, 1],
                ['Cala Pi Club', '10440 North Central Expressway, Suite 400, Dallas, Texas 75231', 1, $created_at, $updated_at, 1],
                ['Camel\'s Spring Club', '', 1, $created_at, $updated_at, 1],
                ['Carpediem Assisi Living Club', '', 1, $created_at, $updated_at, 1],
                ['Casablanca', 'Calzada Martianez 4, 38400,Puerto de la Cruz,Tenerife,spain', 1, $created_at, $updated_at, 1],
                ['Castle View Club', '', 1, $created_at, $updated_at, 1],
                ['Cela Canet Malibu Village', '', 1, $created_at, $updated_at, 1],
                ['Chaofa Country Club', 'Urbanización Chayofa, Los Cristianos, Arona, Tenerife, Canary Islands', 1, $created_at, $updated_at, 1],
                ['Clib Pueblo Canario', 'Urbanizacion Playa Serena 04740 Roquetas de Mar Almeria,Spain', 1, $created_at, $updated_at, 1],
                ['Club Akamas', '', 1, $created_at, $updated_at, 1],
                ['Club Alegria', '', 1, $created_at, $updated_at, 1],
                ['Club Algaida', '', 1, $created_at, $updated_at, 1],
                ['Club Altamira', '', 1, $created_at, $updated_at, 1],
                ['Club Armonia Bodrum Evleri', '', 1, $created_at, $updated_at, 1],
                ['Club Atlantis', '', 1, $created_at, $updated_at, 1],
                ['Club Az?r', '', 1, $created_at, $updated_at, 1],
                ['Club Bellasol', '', 1, $created_at, $updated_at, 1],
                ['Club Calahonda Crown Resort', 'Ur Sitio De Calahonda, Ctra.cadiz Km.196,50, 29650 Mijas, Испания', 1, $created_at, $updated_at, 1],
                ['Club Callao Garden', '', 1, $created_at, $updated_at, 1],
                ['Club Casablanca', '', 1, $created_at, $updated_at, 1],
                ['Club Dedeman Bodrum Evleri', '', 1, $created_at, $updated_at, 1],
                ['Club Delta Mar', '', 1, $created_at, $updated_at, 1],
                ['Club Deseract', 'Spain, blue lagoun street  str.', 1, $created_at, $updated_at, 1],
                ['Club El Beril', 'Calle El Beril,La Calefa,Adeje,Tenerife,Canary Islands.', 1, $created_at, $updated_at, 1],
                ['Club Hotel Eilat', '', 1, $created_at, $updated_at, 1],
                ['Club in Eilat', '', 1, $created_at, $updated_at, 1],
                ['Club La Costa', 'Spain, Canary Islands, Douglas, 28 Finch Road', 1, $created_at, $updated_at, 1],
                ['Club La Costa at Marina del Sol', 'Ctra. de Cádiz km 206, 29649 Mijas Costa, Málaga, Spain', 1, $created_at, $updated_at, 1],
                ['Club La Costa at Sierra Marina', 'Spain, Malaga, Ctra.de Cadiz, Km. 206, Urbanizasation Marina del Sol', 1, $created_at, $updated_at, 1],
                ['Club La Costa Destinations Club', 'Spain, Mijas Costa, Malaga, Ctra. de Cádiz km.206', 1, $created_at, $updated_at, 1],
                ['Club La Costa Resorts & Hotels', 'Ctra.de Cadiz, km 206 29649 mijas Costa,Malaga Spain', 1, $created_at, $updated_at, 1],
                ['Club La Costa Vacaition Club Limited', '', 1, $created_at, $updated_at, 1],
                ['Club La Mar', '', 1, $created_at, $updated_at, 1],
                ['Club La Paz', '', 1, $created_at, $updated_at, 1],
                ['Club las Adelfas II', '', 1, $created_at, $updated_at, 1],
                ['Club Marbella', '', 1, $created_at, $updated_at, 1],
                ['Club Marina', '', 1, $created_at, $updated_at, 1],
                ['Club Maritimo  At Ronda Tres', '', 1, $created_at, $updated_at, 1],
                ['Club Maritimo Ronda Tres', 'Paseo Maritimo Los Boliches 29640 Fuengirola Málaga ESPAÑA', 1, $created_at, $updated_at, 1],
                ['Club Ogisaka Garden', '', 1, $created_at, $updated_at, 1],
                ['Club Olympus', 'Spain, San Eugenio, Tenerife, CANARY ISLANDS', 1, $created_at, $updated_at, 1],
                ['Club Paradise Court', '', 1, $created_at, $updated_at, 1],
                ['Club Parque Albatros', '', 1, $created_at, $updated_at, 1],
                ['Club Parque Mesa del Mar', 'Tacoronte, Canary Islands (Spain) 38358', 1, $created_at, $updated_at, 1],
                ['Club Patara', '', 1, $created_at, $updated_at, 1],
                ['Club Playa Vista', '', 1, $created_at, $updated_at, 1],
                ['Club Primavera', '', 1, $created_at, $updated_at, 1],
                ['Club Pueblo Canario', '', 1, $created_at, $updated_at, 1],
                ['Club Puerto Calma', '', 1, $created_at, $updated_at, 1],
                ['Club Pyla Beach Resort', '', 1, $created_at, $updated_at, 1],
                ['Club San Antonio', '', 1, $created_at, $updated_at, 1],
                ['CLUB SUNSET BUY', '', 1, $created_at, $updated_at, 1],
                ['Club System Vacances', '', 1, $created_at, $updated_at, 1],
                ['Club System Vacation', 'Portal House,Glacis Road,BP 847 GIBRALTAR', 1, $created_at, $updated_at, 1],
                ['CLUB TENERIFE', '', 1, $created_at, $updated_at, 1],
                ['Club Unicum', '', 1, $created_at, $updated_at, 1],
                ['Club Vista Serena', '', 1, $created_at, $updated_at, 1],
                ['Club Vistaflor', '', 1, $created_at, $updated_at, 1],
                ['Colonial Village', 'Los Cardones Avenida Litoral Playa de las Américas Arona, Tenerife Canary Islands,', 1, $created_at, $updated_at, 1],
                ['Colonial Village Bonus week', 'Los Cardones Avenida Litoral Playa de las Américas Arona, Tenerife Canary Islands', 1, $created_at, $updated_at, 1],
                ['Compass Club', '', 1, $created_at, $updated_at, 1],
                ['Concepts Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['CORONA ImpEx LLC', '', 1, $created_at, $updated_at, 1],
                ['Crown Resorts', '', 1, $created_at, $updated_at, 1],
                ['Dhahabi Village end Beach resorts', '', 1, $created_at, $updated_at, 1],
                ['Diamond Club la Cumbre', '', 1, $created_at, $updated_at, 1],
                ['Diamond Club Maritima', 'Calle Mirafondo 3,Puerto del Carmen,Canary Islands', 1, $created_at, $updated_at, 1],
                ['Diamond V.S.I.', '', 1, $created_at, $updated_at, 1],
                ['Dream Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['Dream Works Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['East West Gold Club', '', 1, $created_at, $updated_at, 1],
                ['EL MARQUES PALACE', 'Calle las Rosas, Puerto de Santiago CANARY ISLANDS, SPAIN', 1, $created_at, $updated_at, 1],
                ['El Narankhal', '141 Avenue des Hauts de Canet Canet en Rousillon', 1, $created_at, $updated_at, 1],
                ['El Palmeral Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Estela Dorada', '', 1, $created_at, $updated_at, 1],
                ['Fabus Club', '', 1, $created_at, $updated_at, 1],
                ['Family Trip Cyprus', '', 1, $created_at, $updated_at, 1],
                ['FLAMINGO', 'Calle Princesa Ico, Nº 17 Conjunto Residencial Timanfaya  Puerto del Carmen, Lanzarote Canary Islands', 1, $created_at, $updated_at, 1],
                ['Gold Crown Club Ltd.', '', 1, $created_at, $updated_at, 1],
                ['Golden Aden', 'Bolshaya Ordynka d.17 office № 2 Moscow', 1, $created_at, $updated_at, 1],
                ['Golden Coast Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Grand Holidays Club', '', 1, $created_at, $updated_at, 1],
                ['Grand Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['Grangefield Oasis Club', '', 1, $created_at, $updated_at, 1],
                ['Harbor-2', 'Avenida José González Forte 26,Los Gigantes,Tenerife', 1, $created_at, $updated_at, 1],
                ['Harbour Club', '', 1, $created_at, $updated_at, 1],
                ['Heritage Resorts', 'Urbanización Mijas Golf \r\n29650 Mijas-Costa \r\nMálaga,    \r\nSpain \r\n952-461375', 1, $created_at, $updated_at, 1],
                ['Heritage Resorts Club Playa Real', '', 1, $created_at, $updated_at, 1],
                ['Heritage Resorts Marbesa Club', '', 1, $created_at, $updated_at, 1],
                ['Hever Golf & Country Club Hotel', '', 1, $created_at, $updated_at, 1],
                ['Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Holiday Club Calahonda', '', 1, $created_at, $updated_at, 1],
                ['Holiday International', 'HOTEL HOLIDAY INTERNATIONAL\r\nP O BOX 5802 Sharjah, U.A.E,', 1, $created_at, $updated_at, 1],
                ['Hollywood Mirage Club', '', 1, $created_at, $updated_at, 1],
                ['Imperial Park Country Club', '', 1, $created_at, $updated_at, 1],
                ['Infiniti Club', '', 1, $created_at, $updated_at, 1],
                ['International Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['Interval Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['Iria Mare Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Islande Village', 'San Eugenio Alto, Playa de las Americas, Adeje, Tenerife, Canary Islands', 1, $created_at, $updated_at, 1],
                ['Jalan Raya Candi Dasa', 'Maggis, Amplapura\r\n80851 Karangasem, Bali, Indonesia \r\n363-42191 363-42192 363-42193', 1, $created_at, $updated_at, 1],
                ['Jl. Telaga Waja', 'Banjar Tengkulung\r\n80363 Nusa Dua, Bali, Indonesia\r\n', 1, $created_at, $updated_at, 1],
                ['Jomtien Beach Paradise Club', '', 1, $created_at, $updated_at, 1],
                ['L.O.G.I.C Limited', 'Main Street 65,British Virgin Islands', 1, $created_at, $updated_at, 1],
                ['LA COSTA', 'De Cadiz Km,206.5,Mijias-Costa,Malaga', 1, $created_at, $updated_at, 1],
                ['La Costa at Castillo del Rey', 'Urb.Marina del Sol,Ctra. De Cadiz Km,206.5,Mijias-Costa,Malaga', 1, $created_at, $updated_at, 1],
                ['La Hacienda Club', '', 1, $created_at, $updated_at, 1],
                ['La Paz', 'Avda. Luis Diaz de Losada, No 2, 38660,Tenerife,Spain', 1, $created_at, $updated_at, 1],
                ['La Pinta Beach Club', '', 1, $created_at, $updated_at, 1],
                ['La Quinta at La Manga Club', '', 1, $created_at, $updated_at, 1],
                ['La Riviera', 'Urbanización Riviera del Sol, С/ Saturno s/n Mijas-Costa, Malaga', 1, $created_at, $updated_at, 1],
                ['LAGOS DE FANABE', 'Calle Londres 7, Urb.Playa Fañabé\r\n 38660, Costa Adeje\r\n SC de Tenerife, España', 1, $created_at, $updated_at, 1],
                ['Lagos de Fanabe (Los Olivas)', '', 1, $created_at, $updated_at, 1],
                ['LAGOS DE FANABE 2 Vacation club', '', 1, $created_at, $updated_at, 1],
                ['Lanzarote Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Las Mimosas Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Lenchester', '', 1, $created_at, $updated_at, 1],
                ['Les Villas AT Le Meridien', 'Le Meridien Hotel,Old Limasol Nicosia Road,Limasol', 1, $created_at, $updated_at, 1],
                ['Lion Resorts - Club Alias', '', 1, $created_at, $updated_at, 1],
                ['Los Olivos', 'Apartments Los Olivos C/ Paris, 1 Costa Adeje Tenerife', 1, $created_at, $updated_at, 1],
                ['Majestic Club', '', 1, $created_at, $updated_at, 1],
                ['Malibu Club', '', 1, $created_at, $updated_at, 1],
                ['Maliby Village', '141 Avenue des Hauts de Canet Canet en Rousillon', 1, $created_at, $updated_at, 1],
                ['Marbesa Club', 'C\\O Club Playa Real,Urbanización Marbesa ,Ctra de Cadiz,Malaga', 1, $created_at, $updated_at, 1],
                ['Marina Club Hotel Eilat', '', 1, $created_at, $updated_at, 1],
                ['Marina Palace Club', '', 1, $created_at, $updated_at, 1],
                ['Matchroom Country Club', '', 1, $created_at, $updated_at, 1],
                ['Mesa Del Mar', '', 1, $created_at, $updated_at, 1],
                ['Metropolitan Capsis Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Middle World', '', 1, $created_at, $updated_at, 1],
                ['Miraflores Beach & Country Club', '', 1, $created_at, $updated_at, 1],
                ['MTC PLUS BONUS WEEKS', '266/9 Moo 9, Nongprue Sub-District, Banglamung district, Chonburi Province, Thailand', 1, $created_at, $updated_at, 1],
                ['Multiclub', '78 York Street, London, W1H1DP, UK\r\n+44(0)203-026-58-70', 1, $created_at, $updated_at, 1],
                ['MULTICLUB BONUS WEEK', '78 York Street, London, W1H1DP, UK\r\n+44(0)203-026-58-70', 1, $created_at, $updated_at, 1],
                ['Multiple Travel Club.,LTD', '', 1, $created_at, $updated_at, 1],
                ['Natural Salution', 'Avenida Ernesto Sarti, 5. Playa de Las Americas', 1, $created_at, $updated_at, 1],
                ['Natural Solutions International', '', 1, $created_at, $updated_at, 1],
                ['Oasis club', 'Calle Topacio s/n Urb. Riviera del Sol Mijas-Costa, Málaga', 1, $created_at, $updated_at, 1],
                ['Olympus at Garden City', '', 1, $created_at, $updated_at, 1],
                ['One World Holidays', '', 1, $created_at, $updated_at, 1],
                ['P?lus Palace Thermal Golf Club Hotel', '', 1, $created_at, $updated_at, 1],
                ['Pafiana Heights', 'Pafiana Road\r\nKonia\r\nCY 8102\r\nPaphos, Cyprus \r\n26-813311 \r\n', 1, $created_at, $updated_at, 1],
                ['Palms Golf & Country Club', 'Parcela B I, Golf del Sur,San Migel de Abona,Tenerife,Canary Islands', 1, $created_at, $updated_at, 1],
                ['Panareti\'s Royal Coral Bay Resort', '', 1, $created_at, $updated_at, 1],
                ['Park Lane club', '', 1, $created_at, $updated_at, 1],
                ['Parque del Sol', 'Playa Fañabé 38660 - Costa Adeje \r\nSanta Cruz de Tenerife \r\nIslas Canarias', 1, $created_at, $updated_at, 1],
                ['Pebble Beach Village', '', 1, $created_at, $updated_at, 1],
                ['PERL GREI OCEAN', '', 1, $created_at, $updated_at, 1],
                ['Pólus Palace Thermal Golf Club Hotel', 'Kádár utca 49\r\n2132 Göd, Hungary \r\n06-27-530500 \r\n', 1, $created_at, $updated_at, 1],
                ['PREMIER HOLIDAY CLUB', 'C/El Lajial s/n, local 8\r\n Puerto Santiago, 38683, \r\nTenerife, Spain.', 1, $created_at, $updated_at, 1],
                ['Premium Vacation  Club', '', 1, $created_at, $updated_at, 1],
                ['Puerto Colon Club', '', 1, $created_at, $updated_at, 1],
                ['Pyramisa Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Quality Vacation Club', '', 1, $created_at, $updated_at, 1],
                ['Radisson Blu Resort & Spa ', 'Na Moru 1\r\nOrasac 20234\r\nDubrovnik, Croatia \r\n00385 20 361 500 \r\n', 1, $created_at, $updated_at, 1],
                ['RCI POINTS CLUB', '', 1, $created_at, $updated_at, 1],
                ['Regency Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Regency Club', '', 1, $created_at, $updated_at, 1],
                ['Regency Country Club', '', 1, $created_at, $updated_at, 1],
                ['Regency Height Neptuno', 'c/o The Regency Club ,Adeje,Canary Islands', 1, $created_at, $updated_at, 1],
                ['Regency Heights at Neptuno', 'Urbanizacion Tingufaya, 38660 Playa de las Americas, Tenerife, Spain', 1, $created_at, $updated_at, 1],
                ['Resort Montana Vista Club', '', 1, $created_at, $updated_at, 1],
                ['Rock World Wide Ltd', 'P. O. Box 320075\r\nFairfield, CT 06825', 1, $created_at, $updated_at, 1],
                ['Royal Atlantic', 'PO Box 936 Montauk, NY 11954\r\n126 South Edgemere Street Montauk, NY 11954', 1, $created_at, $updated_at, 1],
                ['Royal Atlantic Club', '', 1, $created_at, $updated_at, 1],
                ['Royal Club At The Palm', '', 1, $created_at, $updated_at, 1],
                ['Royal Crown Club', '', 1, $created_at, $updated_at, 1],
                ['Royal Garden', '8217 E. Tryon Grove Rd.\r\n Richmond, IL 60071', 1, $created_at, $updated_at, 1],
                ['Royal Gardens at Sunset Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Royal Goan Beach', 'Sam-San Travels\r\n3, Dwarka, Shastri Hall, Tardeo Road, Mumbai: 400 007, India', 1, $created_at, $updated_at, 1],
                ['Royal Park Albatros Club', '', 1, $created_at, $updated_at, 1],
                ['Royal pleaser', '', 1, $created_at, $updated_at, 1],
                ['Royal Sun Resort', '', 1, $created_at, $updated_at, 1],
                ['Royal Sunset Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Royal Sunset Heights Club', '', 1, $created_at, $updated_at, 1],
                ['Royal Tenerife Country Club', '', 1, $created_at, $updated_at, 1],
                ['Royale Marketing LTD', '', 1, $created_at, $updated_at, 1],
                ['S Holiday', '', 1, $created_at, $updated_at, 1],
                ['Sand Club', '', 1, $created_at, $updated_at, 1],
                ['Santa Barbara Gold And Okean Club', '', 1, $created_at, $updated_at, 1],
                ['SELECT VACATION CLUB', '', 1, $created_at, $updated_at, 1],
                ['SES Fontanellas Plaza Club', 'C/ El Lajial, local 8, Puerto Santiago, Tenerife\r\n \r\n38683 Santiago del Teide, Islas Canarias', 1, $created_at, $updated_at, 1],
                ['Sindbad Beach Club', '', 1, $created_at, $updated_at, 1],
                ['Sindbad Beach Resorts Club', 'Hurghada,Red Sea', 1, $created_at, $updated_at, 1],
                ['SPACE TRAVEL', 'Spain, Peel Street, Isli of Man, IM8, next to Waterslide Park', 1, $created_at, $updated_at, 1],
                ['SPACETRAVEL', 'Calle Antonio Navarro 1 Urb. Torviscas Costa Adeje, Tenerife Canary Islands', 1, $created_at, $updated_at, 1],
                ['Sun Beach Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Sunningdale Village', 'Golf del Sur San Miguel de Abona, Tenerife, Canary Islands', 1, $created_at, $updated_at, 1],
                ['Sunningdale Village club, Vacation club', '', 1, $created_at, $updated_at, 1],
                ['SUNSET BAY CLUB', '', 1, $created_at, $updated_at, 1],
                ['Sunset Beach Club', 'Avenida del Sol, 5 – E–29630 Benalmádena Costa – Málaga, Spain', 1, $created_at, $updated_at, 1],
                ['Sunset View', 'San Miguel de Abona , Tenerife, Canary Islands', 1, $created_at, $updated_at, 1],
                ['Sunset View Club', '', 1, $created_at, $updated_at, 1],
                ['Szalajka Liget Hotel & Apartment Houses', '', 1, $created_at, $updated_at, 1],
                ['Tenerife', '', 1, $created_at, $updated_at, 1],
                ['Tenerife Royal Garden', 'Calle Luis de Losada, 7, 38650\r\nPlaya de las Americas, Spain', 1, $created_at, $updated_at, 1],
                ['The Discovery Club', '', 1, $created_at, $updated_at, 1],
                ['The Harbour club', 'Avenida José González Forte 26,Los Gigantes,Tenerife', 1, $created_at, $updated_at, 1],
                ['The Kingfisher Club Benal Beach', '', 1, $created_at, $updated_at, 1],
                ['The Lanzarote Club', 'Avenida de las Islas Costa Teguise, Canary Islands Costa Teguise, Canary Islands', 1, $created_at, $updated_at, 1],
                ['The Palm Beach Club', '', 1, $created_at, $updated_at, 1],
                ['The Palm Golf & Country Club', '', 1, $created_at, $updated_at, 1],
                ['The Regency Club Tenerife', '', 1, $created_at, $updated_at, 1],
                ['The Villas at Chayofa Country Club', '', 1, $created_at, $updated_at, 1],
                ['THE WALTON HALL CLUB', 'Walton,Wellesbourne,Warwickshire CV35 9HU England', 1, $created_at, $updated_at, 1],
                ['TORRENT BAY CLUB', 'Urbanización Ses Bledas,Calle Valencia 4,San Antonio Abad,Islas Baleares', 1, $created_at, $updated_at, 1],
                ['United Paradise', '', 1, $created_at, $updated_at, 1],
                ['Valton Harbor', 'Calle Sierra Nevada S/N, Urbanizacion Oasis del Sur, Los Cristianos, Arona Tenerife, Canary Islands', 1, $created_at, $updated_at, 1],
                ['VEGA Inc Club', 'Le Meridien Hotel,Old Limasol Nicosia Road,Limasol', 1, $created_at, $updated_at, 1],
                ['Vera Beach Club', 'Avda. Juan S El Cano S/N, Urb. Pueblo Laguna, Vera, Almeria', 1, $created_at, $updated_at, 1],
                ['Vetley LTD.', 'Carretera Puerto Santiago 58, Puerto de Santiago Tenerife, Canary Islands', 1, $created_at, $updated_at, 1],
                ['View Talay', '404/66 Moo 12, Jomtien Beach Nongprue, Banglamung Chonburi 20260, THAILAND', 1, $created_at, $updated_at, 1],
                ['View Talay Holiday Resort', '', 1, $created_at, $updated_at, 1],
                ['Vigilia Park', 'Avenida Quinto Centenario N. 58, 38683 Puerto de Santiago,', 1, $created_at, $updated_at, 1],
                ['Viva Club', '112/13 Moo5,Nongprue,Barglamung,Chonburi. 20260, Thailand', 1, $created_at, $updated_at, 1],
                ['Walton Hall', '', 1, $created_at, $updated_at, 1],
                ['Waterman Holiday Club', '', 1, $created_at, $updated_at, 1],
                ['Yucca Park', 'Calle Londres Tr B 8,Playa de Fañabe, Adeje, Spain,Tenerife', 1, $created_at, $updated_at, 1],
                ['Zahabia Village & Beach Resorts', '', 1, $created_at, $updated_at, 1],
                ['Мирафлорес Вакейшн Клаб', '', 1, $created_at, $updated_at, 1]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable('{{%clubs}}');
    }
}
