<?php

use yii\db\Migration;

/**
 * Handles the creation of table `countries`.
 */
class m161130_144925_create_countries_table extends Migration
{
    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTable('{{%countries}}', [
            'id' => $this->primaryKey(),
            'name' => $this->string(128)->notNull()->unique(),
            'full_name' => $this->text()->notNull(),
            'iso_3166' => $this->text()->notNull(),
            'is_active' => $this->integer(1)->notNull(),
            'created_at' => $this->integer()->notNull(),
            'updated_at' => $this->integer()->notNull(),
            'is_active_server' => $this->integer(1)
        ]);

        $created_at = $updated_at = date("Ymd");

        $this->batchInsert('{{%countries}}', ['name', 'full_name', 'iso_3166', 'created_at', 'updated_at','is_active', 'is_active_server'], [
                ['Afghanistan', 'Islamic Republic of Afghanistan', 'AF', $created_at, $updated_at,1,1],
                ['Albania', 'Republic of Albania', 'AL', $created_at, $updated_at,1,1],
                ['Algeria', 'People\'s Democratic Republic of Algeria', 'DZ', $created_at, $updated_at,1,1],
                ['Andorra', 'Principality of Andorra', 'AD', $created_at, $updated_at,1,1],
                ['Angola', 'Republic of Angola', 'AO', $created_at, $updated_at,1,1],
                ['Antigua and Barbuda', 'Antigua and Barbuda', 'AG', $created_at, $updated_at,1,1],
                ['Argentina', 'Argentine Republic[A]', 'AR', $created_at, $updated_at,1,1],
                ['Armenia', 'Republic of Armenia', 'AM', $created_at, $updated_at,1,1],
                ['Australia', 'Commonwealth of Australia', 'AU', $created_at, $updated_at,1,1],
                ['Austria', 'Republic of Austria', 'AT', $created_at, $updated_at,1,1],
                ['Azerbaijan', 'Republic of Azerbaijan', 'AZ', $created_at, $updated_at,1,1],
                ['Bahamas, The', 'Commonwealth of the Bahamas', 'BS', $created_at, $updated_at,1,1],
                ['Bahrain', 'Kingdom of Bahrain', 'BH', $created_at, $updated_at,1,1],
                ['Bangladesh', 'People\'s Republic of Bangladesh', 'BD', $created_at, $updated_at,1,1],
                ['Barbados', 'Barbados', 'BB', $created_at, $updated_at,1,1],
                ['Belarus', 'Republic of Belarus', 'BY', $created_at, $updated_at,1,1],
                ['Belgium', 'Kingdom of Belgium', 'BE', $created_at, $updated_at,1,1],
                ['Belize', 'Belize', 'BZ', $created_at, $updated_at,1,1],
                ['Benin', 'Republic of Benin', 'BJ', $created_at, $updated_at,1,1],
                ['Bhutan', 'Kingdom of Bhutan', 'BT', $created_at, $updated_at,1,1],
                ['Bolivia', 'Plurinational State of Bolivia', 'BO', $created_at, $updated_at,1,1],
                ['Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BA', $created_at, $updated_at,1,1],
                ['Botswana', 'Republic of Botswana', 'BW', $created_at, $updated_at,1,1],
                ['Brazil', 'Federative Republic of Brazil', 'BR', $created_at, $updated_at,1,1],
                ['Brunei', 'Nation of Brunei, Abode of Peace', 'BN', $created_at, $updated_at,1,1],
                ['Bulgaria', 'Republic of Bulgaria', 'BG', $created_at, $updated_at,1,1],
                ['Burkina Faso', 'Burkina Faso', 'BF', $created_at, $updated_at,1,1],
                ['Burundi', 'Republic of Burundi', 'BI', $created_at, $updated_at,1,1],
                ['Cambodia', 'Kingdom of Cambodia', 'KH', $created_at, $updated_at,1,1],
                ['Cameroon', 'Republic of Cameroon', 'CM', $created_at, $updated_at,1,1],
                ['Canada', '', 'CA', $created_at, $updated_at,1,1],
                ['Cape Verde', 'Republic of Cabo Verde', 'CV', $created_at, $updated_at,1,1],
                ['Central African Republic', 'Central African Republic', 'CF', $created_at, $updated_at,1,1],
                ['Chad', 'Republic of Chad', 'TD', $created_at, $updated_at,1,1],
                ['Chile', 'Republic of Chile', 'CL', $created_at, $updated_at,1,1],
                ['China', 'People\'s Republic of China', 'CN', $created_at, $updated_at,1,1],
                ['Colombia', 'Republic of Colombia', 'CO', $created_at, $updated_at,1,1],
                ['Comoros', 'Union of the Comoros', 'KM', $created_at, $updated_at,1,1],
                ['Congo, Democratic Republic of the', 'Democratic Republic of the Congo', 'CD', $created_at, $updated_at,1,1],
                ['Congo, Republic of the', 'Republic of the Congo', 'CG', $created_at, $updated_at,1,1],
                ['Costa Rica', 'Republic of Costa Rica', 'CR', $created_at, $updated_at,1,1],
                ['Croatia', 'Republic of Croatia', 'HR', $created_at, $updated_at,1,1],
                ['Cuba', 'Republic of Cuba', 'CU', $created_at, $updated_at,1,1],
                ['Cyprus', 'Republic of Cyprus', 'CY', $created_at, $updated_at,1,1],
                ['Czech Republic', 'Czech Republic', 'CZ', $created_at, $updated_at,1,1],
                ['Denmark', 'Kingdom of Denmark', 'DK', $created_at, $updated_at,1,1],
                ['Djibouti', 'Republic of Djibouti', 'DJ', $created_at, $updated_at,1,1],
                ['Dominica', 'Commonwealth of Dominica', 'DM', $created_at, $updated_at,1,1],
                ['Dominican Republic', 'Dominican Republic', 'DO', $created_at, $updated_at,1,1],
                ['East Timor', 'Democratic Republic of Timor-Leste', 'TL', $created_at, $updated_at,1,1],
                ['Ecuador', 'Republic of Ecuador', 'EC', $created_at, $updated_at,1,1],
                ['Egypt', 'Arab Republic of Egypt', 'EG', $created_at, $updated_at,1,1],
                ['El Salvador', 'Republic of El Salvador', 'SV', $created_at, $updated_at,1,1],
                ['Equatorial Guinea', 'Republic of Equatorial Guinea', 'GQ', $created_at, $updated_at,1,1],
                ['Eritrea', 'State of Eritrea', 'ER', $created_at, $updated_at,1,1],
                ['Estonia', 'Republic of Estonia', 'EE', $created_at, $updated_at,1,1],
                ['Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ET', $created_at, $updated_at,1,1],
                ['Fiji', 'Republic of Fiji', 'FJ', $created_at, $updated_at,1,1],
                ['Finland', 'Republic of Finland', 'FI', $created_at, $updated_at,1,1],
                ['France', 'French Republic', 'FR', $created_at, $updated_at,1,1],
                ['Gabon', 'Gabonese Republic', 'GA', $created_at, $updated_at,1,1],
                ['Gambia, The', 'Islamic Republic of The Gambia', 'GM', $created_at, $updated_at,1,1],
                ['Georgia', 'Georgia', 'GE', $created_at, $updated_at,1,1],
                ['Germany', 'Federal Republic of Germany', 'DE', $created_at, $updated_at,1,1],
                ['Ghana', 'Republic of Ghana', 'GH', $created_at, $updated_at,1,1],
                ['Greece', 'Hellenic Republic', 'GR', $created_at, $updated_at,1,1],
                ['Grenada', '', 'GD', $created_at, $updated_at,1,1],
                ['Guatemala', 'Republic of Guatemala', 'GT', $created_at, $updated_at,1,1],
                ['Guinea', 'Republic of Guinea', 'GN', $created_at, $updated_at,1,1],
                ['Guinea-Bissau', 'Republic of Guinea-Bissau', 'GW', $created_at, $updated_at,1,1],
                ['Guyana', 'Co-operative Republic of Guyana', 'GY', $created_at, $updated_at,1,1],
                ['Haiti', 'Republic of Haiti', 'HT', $created_at, $updated_at,1,1],
                ['Honduras', 'Republic of Honduras', 'HN', $created_at, $updated_at,1,1],
                ['Hungary', 'Hungary', 'HU', $created_at, $updated_at,1,1],
                ['Iceland', 'Republic of Iceland', 'IS', $created_at, $updated_at,1,1],
                ['India', 'Republic of India', 'IN', $created_at, $updated_at,1,1],
                ['Indonesia', 'Republic of Indonesia', 'ID', $created_at, $updated_at,1,1],
                ['Iran', 'Islamic Republic of Iran', 'IR', $created_at, $updated_at,1,1],
                ['Iraq', 'Republic of Iraq', 'IQ', $created_at, $updated_at,1,1],
                ['Ireland', 'Ireland[a]', 'IE', $created_at, $updated_at,1,1],
                ['Israel', 'State of Israel', 'IL', $created_at, $updated_at,1,1],
                ['Italy', 'Italian Republic', 'IT', $created_at, $updated_at,1,1],
                ['Ivory Coast', 'Republic of Côte dIvoire', 'CI', $created_at, $updated_at,1,1],
                ['Jamaica', 'Jamaica', 'JM', $created_at, $updated_at,1,1],
                ['Japan', 'Japan', 'JP', $created_at, $updated_at,1,1],
                ['Jordan', 'The Hashemite Kingdom of Jordan', 'JO', $created_at, $updated_at,1,1],
                ['Kazakhstan', 'Republic of Kazakhstan', 'KZ', $created_at, $updated_at,1,1],
                ['Kenya', 'Republic of Kenya', 'KE', $created_at, $updated_at,1,1],
                ['Kiribati', 'Republic of Kiribati', 'KI', $created_at, $updated_at,1,1],
                ['Korea, North', 'Democratic People\'s Republic of Korea', 'KP', $created_at, $updated_at,1,1],
                ['Korea, South', 'Republic of Korea', 'KR', $created_at, $updated_at,1,1],
                ['Kuwait', 'State of Kuwait', 'KW', $created_at, $updated_at,1,1],
                ['Kyrgyzstan', 'Kyrgyz Republic', 'KG', $created_at, $updated_at,1,1],
                ['Laos', 'Lao People\'s Democratic Republic', 'LA', $created_at, $updated_at,1,1],
                ['Latvia', 'Republic of Latvia', 'LV', $created_at, $updated_at,1,1],
                ['Lebanon', 'Lebanese Republic', 'LB', $created_at, $updated_at,1,1],
                ['Lesotho', 'Kingdom of Lesotho', 'LS', $created_at, $updated_at,1,1],
                ['Liberia', 'Republic of Liberia', 'LR', $created_at, $updated_at,1,1],
                ['Libya', 'Libya', 'LY', $created_at, $updated_at,1,1],
                ['Liechtenstein', 'Principality of Liechtenstein', 'LI', $created_at, $updated_at,1,1],
                ['Lithuania', 'Republic of Lithuania', 'LT', $created_at, $updated_at,1,1],
                ['Luxembourg', 'Grand Duchy of Luxembourg', 'LU', $created_at, $updated_at,1,1],
                ['Macedonia', 'Republic of Macedonia', 'MK', $created_at, $updated_at,1,1],
                ['Madagascar', 'Republic of Madagascar', 'MG', $created_at, $updated_at,1,1],
                ['Malawi', 'Republic of Malawi', 'MW', $created_at, $updated_at,1,1],
                ['Malaysia', 'Malaysia', 'MY', $created_at, $updated_at,1,1],
                ['Maldives', 'Republic of Maldives', 'MV', $created_at, $updated_at,1,1],
                ['Mali', 'Republic of Mali', 'ML', $created_at, $updated_at,1,1],
                ['Malta', 'Republic of Malta', 'MT', $created_at, $updated_at,1,1],
                ['Marshall Islands', 'Republic of the Marshall Islands', 'MH', $created_at, $updated_at,1,1],
                ['Mauritania', 'Islamic Republic of Mauritania', 'MR', $created_at, $updated_at,1,1],
                ['Mauritius', 'Republic of Mauritius', 'MU', $created_at, $updated_at,1,1],
                ['Mexico', 'United Mexican States', 'MX', $created_at, $updated_at,1,1],
                ['Micronesia', 'Federated States of Micronesia', 'FM', $created_at, $updated_at,1,1],
                ['Moldova', 'Republic of Moldova', 'MD', $created_at, $updated_at,1,1],
                ['Monaco', 'Principality of Monaco', 'MC', $created_at, $updated_at,1,1],
                ['Mongolia', 'Mongolia', 'MN', $created_at, $updated_at,1,1],
                ['Montenegro', 'Montenegro', 'ME', $created_at, $updated_at,1,1],
                ['Morocco', 'Kingdom of Morocco', 'MA', $created_at, $updated_at,1,1],
                ['Mozambique', 'Republic of Mozambique', 'MZ', $created_at, $updated_at,1,1],
                ['Myanmar', 'Republic of the Union of Myanmar', 'MM', $created_at, $updated_at,1,1],
                ['Namibia', '', 'NA', $created_at, $updated_at,1,1],
                ['Nauru', 'Republic of Nauru', 'NR', $created_at, $updated_at,1,1],
                ['Nepal', 'Federal Democratic Republic of Nepal', 'NP', $created_at, $updated_at,1,1],
                ['Netherlands', 'Kingdom of the Netherlands', '', $created_at, $updated_at,1,1],
                ['New Zealand', 'New Zealand', 'NZ', $created_at, $updated_at,1,1],
                ['Nicaragua', 'Republic of Nicaragua', 'NI', $created_at, $updated_at,1,1],
                ['Niger', 'Republic of Niger', 'NE', $created_at, $updated_at,1,1],
                ['Nigeria', 'Federal Republic of Nigeria', 'NG', $created_at, $updated_at,1,1],
                ['Norway', 'Kingdom of Norway', 'NO', $created_at, $updated_at,1,1],
                ['Oman', 'Sultanate of Oman', 'OM', $created_at, $updated_at,1,1],
                ['Pakistan', 'Islamic Republic of Pakistan', 'PK', $created_at, $updated_at,1,1],
                ['Palau', 'Republic of Palau', 'PW', $created_at, $updated_at,1,1],
                ['Palestine', 'State of Palestine[i]', 'PS', $created_at, $updated_at,1,1],
                ['Panama', 'Republic of Panama', 'PA', $created_at, $updated_at,1,1],
                ['Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', $created_at, $updated_at,1,1],
                ['Paraguay', 'Republic of Paraguay', 'PY', $created_at, $updated_at,1,1],
                ['Peru', 'Republic of Peru', 'PE', $created_at, $updated_at,1,1],
                ['Philippines', 'Republic of the Philippines', 'PH', $created_at, $updated_at,1,1],
                ['Poland', 'Republic of Poland', 'PL', $created_at, $updated_at,1,1],
                ['Portugal', 'Portuguese Republic', 'PT', $created_at, $updated_at,1,1],
                ['Qatar', 'State of Qatar', 'QA', $created_at, $updated_at,1,1],
                ['Romania', 'Romania', 'RO', $created_at, $updated_at,1,1],
                ['Russia', 'Russian Federation', 'RU', $created_at, $updated_at,1,1],
                ['Rwanda', 'Republic of Rwanda', 'RW', $created_at, $updated_at,1,1],
                ['Saint Kitts and Nevis', 'Federation of Saint Kitts and Nevis', 'KN', $created_at, $updated_at,1,1],
                ['Saint Lucia', 'Saint Lucia', 'LC', $created_at, $updated_at,1,1],
                ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', $created_at, $updated_at,1,1],
                ['Samoa', 'Independent State of Samoa', 'WS', $created_at, $updated_at,1,1],
                ['San Marino', 'Republic of San Marino[1][2]', 'SM', $created_at, $updated_at,1,1],
                ['São Tomé and Príncipe', 'Democratic Republic of
São Tomé and Príncipe', 'ST', $created_at, $updated_at,1,1],
                ['Saudi Arabia', 'Kingdom of Saudi Arabia', 'SA', $created_at, $updated_at,1,1],
                ['Senegal', 'Republic of Senegal', 'SN', $created_at, $updated_at,1,1],
                ['Serbia', 'Republic of Serbia', 'RS', $created_at, $updated_at,1,1],
                ['Seychelles', 'Republic of Seychelles', 'SC', $created_at, $updated_at,1,1],
                ['Sierra Leone', 'Republic of Sierra Leone', 'SL', $created_at, $updated_at,1,1],
                ['Singapore', 'Republic of Singapore', 'SG', $created_at, $updated_at,1,1],
                ['Slovakia', 'Slovak Republic', 'SK', $created_at, $updated_at,1,1],
                ['Slovenia', 'Republic of Slovenia', 'SI', $created_at, $updated_at,1,1],
                ['Solomon Islands', 'Solomon Islands', 'SB', $created_at, $updated_at,1,1],
                ['Somalia', 'Federal Republic of Somalia[1]', 'SO', $created_at, $updated_at,1,1],
                ['South Africa', '', 'ZA', $created_at, $updated_at,1,1],
                ['South Sudan', 'Republic of South Sudan', 'SS', $created_at, $updated_at,1,1],
                ['Spain', 'Kingdom of Spain', 'ES', $created_at, $updated_at,1,1],
                ['Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LK', $created_at, $updated_at,1,1],
                ['Sudan', 'Republic of the Sudan', 'SD', $created_at, $updated_at,1,1],
                ['Suriname', 'Republic of Suriname', 'SR', $created_at, $updated_at,1,1],
                ['Swaziland', 'Kingdom of Swaziland', 'SZ', $created_at, $updated_at,1,1],
                ['Sweden', 'Kingdom of Sweden', 'SE', $created_at, $updated_at,1,1],
                ['Switzerland', 'Swiss Confederation', 'CH', $created_at, $updated_at,1,1],
                ['Syria', 'Syrian Arab Republic', 'SY', $created_at, $updated_at,1,1],
                ['Tajikistan', 'Republic of Tajikistan', 'TJ', $created_at, $updated_at,1,1],
                ['Tanzania', 'United Republic of Tanzania', 'TZ', $created_at, $updated_at,1,1],
                ['Thailand', 'Kingdom of Thailand', 'TH', $created_at, $updated_at,1,1],
                ['Togo', 'Togolese Republic', 'TG', $created_at, $updated_at,1,1],
                ['Tonga', 'Kingdom of Tonga', 'TO', $created_at, $updated_at,1,1],
                ['Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TT', $created_at, $updated_at,1,1],
                ['Tunisia', 'Tunisian Republic', 'TN', $created_at, $updated_at,1,1],
                ['Turkey', 'Republic of Turkey', 'TR', $created_at, $updated_at,1,1],
                ['Turkmenistan', 'Turkmenistan', 'TM', $created_at, $updated_at,1,1],
                ['Tuvalu', 'Tuvalu', 'TV', $created_at, $updated_at,1,1],
                ['Uganda', 'Republic of Uganda', 'UG', $created_at, $updated_at,1,1],
                ['Ukraine', 'Ukraine', 'UA', $created_at, $updated_at,1,1],
                ['United Arab Emirates', 'United Arab Emirates', 'AE', $created_at, $updated_at,1,1],
                ['United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'GB', $created_at, $updated_at,1,1],
                ['United States', 'United States of America', 'US', $created_at, $updated_at,1,1],
                ['Uruguay', 'Oriental Republic of Uruguay', 'UY', $created_at, $updated_at,1,1],
                ['Uzbekistan', 'Republic of Uzbekistan', 'UZ', $created_at, $updated_at,1,1],
                ['Vanuatu', 'Republic of Vanuatu', 'VU', $created_at, $updated_at,1,1],
                ['Vatican City', 'Vatican City State', 'VA', $created_at, $updated_at,1,1],
                ['Venezuela', 'Bolivarian Republic of Venezuela[a]', 'VE', $created_at, $updated_at,1,1],
                ['Vietnam', 'Socialist Republic of Vietnam', 'VN', $created_at, $updated_at,1,1],
                ['Yemen', 'Republic of Yemen', 'YE', $created_at, $updated_at,1,1],
                ['Zambia', 'Republic of Zambia', 'ZM', $created_at, $updated_at,1,1],
                ['Zimbabwe', 'Republic of Zimbabwe', 'ZW', $created_at, $updated_at,1,1],
                ['Abkhazia', 'Republic of Abkhazia', '', $created_at, $updated_at,1,1],
                ['Cook Islands', 'Cook Islands', 'CK', $created_at, $updated_at,1,1],
                ['Kosovo', 'Republic of Kosovo', 'XK', $created_at, $updated_at,1,1],
                ['Nagorno-Karabakh', 'Nagorno-Karabakh Republic', '', $created_at, $updated_at,1,1],
                ['Niue', 'Niue', 'NU', $created_at, $updated_at,1,1],
                ['Northern Cyprus', 'Turkish Republic of Northern Cyprus', '', $created_at, $updated_at,1,1],
                ['Sahrawi Arab Democratic Republic', 'Sahrawi Arab Democratic Republic', '', $created_at, $updated_at,1,1],
                ['Somaliland', 'Republic of Somaliland', '', $created_at, $updated_at,1,1],
                ['South Ossetia', 'Republic of South Ossetia', '', $created_at, $updated_at,1,1],
                ['Taiwan', 'Republic of China', 'TW', $created_at, $updated_at,1,1],
                ['Transnistria', 'Pridnestrovian Moldavian Republic', '', $created_at, $updated_at,1,1]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable('{{%countries}}');
    }
}
